### ISSUE TITLE
artifacts from ?C function

### ISSUE THREAD

**Issue by brroberts1231** [phetsims/function-builder-basics#18] opened 2017-05-03 20:21 UTC
For phetsims/tasks#828 

There are some results when using some certain combinations of functions like `?C > Mirror > ?C` that have weird looking artifacts, white lines and misaligned sections. That combination of functions should end up only mirroring the object in the end, but as a result of some tiny asymmetries, the resulting mirrored object has extra lines in it that shouldn't be there. I'm sure this isn't an incredibly important bug, and it requires a really specific setup, but I believe it's worth noting. 

All of the screenshots below are using `C > Mirror > ?C`, but there are other combos like `?C > ?A> ?C` or `?C > ?B > ?C` that do similar things. Basically any function that splits up the picture and then stitches it back together has these lines. 

[@pixelzoom note: I edited the above description to use ?A, ?B, ?C for mystery function names.]

Screenshots: 
![screen shot 2017-05-03 at 2 12 58 pm](https://cloud.githubusercontent.com/assets/11947677/25679464/b14bdac8-300a-11e7-9f92-70d057d0773c.png)
![screen shot 2017-05-03 at 2 14 19 pm](https://cloud.githubusercontent.com/assets/11947677/25679503/d6e119c4-300a-11e7-88bc-8a66636897bb.png)
![screen shot 2017-05-03 at 2 15 04 pm](https://cloud.githubusercontent.com/assets/11947677/25679540/f0fe2f2c-300a-11e7-9db9-7b37faf40e72.png)

Tested on Mac 10.10.5 Safari.

Troubleshooting information (do not edit):
Name: ‪Function Builder: Basics‬
URL: http://www.colorado.edu/physics/phet/dev/html/function-builder-basics/1.0.0-rc.1/function-builder-basics_en.html
Version: 1.0.0-rc.1 2017-05-01 17:32:46 UTC
Features missing: touch
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/601.2.7 (KHTML, like Gecko) Version/9.0.1 Safari/601.2.7
Language: en-us
Window: 1203x647
Pixel Ratio: 1/1
WebGL: WebGL 1.0 (2.1 INTEL-10.0.35)
GLSL: WebGL GLSL ES 1.0 (1.20)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 15 uniform: 1024
Texture: size: 4096 imageUnits: 16 (vertex: 16, combined: 16)
Max viewport: 8192x8192
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"5c3f9204","branch":"HEAD"},"axon":{"sha":"00436448","branch":"HEAD"},"babel":{"sha":"1c04e4e9","branch":"master"},"brand":{"sha":"a4d6573f","branch":"HEAD"},"chipper":{"sha":"628cdd7d","branch":"HEAD"},"dot":{"sha":"f56a4411","branch":"HEAD"},"function-builder":{"sha":"518774f5","branch":"HEAD"},"function-builder-basics":{"sha":"0dc629db","branch":"HEAD"},"joist":{"sha":"deef1bf3","branch":"HEAD"},"kite":{"sha":"2d9c9d84","branch":"HEAD"},"phet-core":{"sha":"76ec0204","branch":"HEAD"},"phetcommon":{"sha":"d0ffe176","branch":"HEAD"},"query-string-machine":{"sha":"e7055778","branch":"HEAD"},"scenery":{"sha":"69953c5c","branch":"HEAD"},"scenery-phet":{"sha":"8707a265","branch":"HEAD"},"sherpa":{"sha":"0e326d54","branch":"HEAD"},"sun":{"sha":"cfea9c5a","branch":"HEAD"},"tandem":{"sha":"30603e66","branch":"HEAD"},"twixt":{"sha":"b1488b51","branch":"HEAD"}}

**Comment by pixelzoom** [comment] 2017-05-03 20:25
@brroberts1231 two questions:

(1) Do the artifacts go away if you resize the browser window?

(2) Is this problem present in the published version of Function Builder? 
1.0.6 at https://phet.colorado.edu/en/simulation/function-builder

**Comment by amanda-phet** [comment] 2017-05-03 20:27
It definitely seems to be specific to ?c, and using it twice, based on what you describe.

**Comment by pixelzoom** [comment] 2017-05-03 20:29
(3) Is it only combination that contain mystery function (?A, ?B, ?C) that have this problem? Or can you reproduce the problem with a combination that does not include a mystery function?

**Comment by pixelzoom** [comment] 2017-05-03 20:36
With `?C > Mirror > ?C`, I see the artifacts on the following platforms:

• Mac OS 10.11.6 + Safari 10.1
• Mac OS 10.11.6 + Chrome 57
• Mac OS 10.11.6 + Firefox 51

... and I see it in FB:B 1.0.0-rc.1, FB:B master, and FB 1.0.6 (production).

So this is not platform specific, and it's likely been a problem since FB 1.0.0.

**Comment by pixelzoom** [comment] 2017-05-03 20:37
I also see the artifacts with `?C > ?A > ?C` and `?C > ?B > ?C`.

**Comment by pixelzoom** [comment] 2017-05-03 20:38
To be clear, here are the problematic configurations:

![screenshot_20](https://cloud.githubusercontent.com/assets/3046552/25680427/0cd0815c-300e-11e7-8450-6c22a601ef4b.png)
![screenshot_22](https://cloud.githubusercontent.com/assets/3046552/25680444/1a3ecb46-300e-11e7-9e3a-10284a58f58b.png)
![screenshot_23](https://cloud.githubusercontent.com/assets/3046552/25680453/2055140e-300e-11e7-9a7e-2262e4c82f7d.png)

**Comment by pixelzoom** [comment] 2017-05-03 20:40
Here are a couple more that have the same problem:

![screenshot_25](https://cloud.githubusercontent.com/assets/3046552/25680523/5ff5e250-300e-11e7-98dc-d76d93db6128.png)
![screenshot_24](https://cloud.githubusercontent.com/assets/3046552/25680526/61312c9c-300e-11e7-8554-f2d3f1456c56.png)

**Comment by brroberts1231** [comment] 2017-05-03 20:40
1. They stay when resizing the window.
2. Yes, it does happen in the published version.
3. So far, the ones you just listed are the only ones I know of.

**Comment by pixelzoom** [comment] 2017-05-03 20:45
?A is a reflection about the x axis (similar to Mirror, but around the horizontal axis).

?B reflects about the y-axis and rotates 90 degrees clockwise (equivalent to "Mirror > Rotate90").

?C divides the image into 4 quadrants and shifts them clockwise (unlike any of the other functions).

So I'm guess that this is a problem with ?C that is only exposed when it's applied twice with a reflection or rotation in the middle.

**Comment by pixelzoom** [comment] 2017-05-03 20:56
Looking at the implementation of `MysteryC.apply`, my next guess is that this is a problem when the width or height of `input` canvas is an odd number.  In that case we may be shifting the same "line" of pixels twice.

I'm wondering if `drawImage` supports sub-pixel locations and dimensions. The function in question is:

```js
CanvasRenderingContext2D.drawImage(image, sx, sy, sWidth, sHeight, dx, dy, dWidth, dHeight);
```

Doc at https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/drawImage

**Comment by pixelzoom** [comment] 2017-05-03 21:36
My hypothesis appears to be correct...  If I guarantee that the cards have a Canvas whose dimensions are even numbers, the problem goes away.   The change in `FBCanvasUtils.createCanvasWithImage` is:

```js
      // Create a canvas whose dimensions are even numbers. Image manipulation functions (MysteryC specifically) will leave artifacts if
      // the dimensions are not even, due to anti-aliasing. See https://github.com/phetsims/function-builder-basics/issues/18
44      canvas.width = image.width + ( image.width % 2 === 0 ? 0 : 1 );
45      canvas.height = image.height + ( image.height % 2 === 0 ? 0 : 1 );
```

**Comment by pixelzoom** [comment] 2017-05-03 22:01
Canvas dimensions are determined by HTMLImageElement dimensions.  If a card image (PNG file) has an odd dimension, there will be a visual artifact (line) perpendicular to the axis of that dimension.  E.g. 200x211 will have a horizontal artifact.  A card whose image has 2 even dimensions has no artifacts.

**Comment by pixelzoom** [comment] 2017-05-03 22:03
Reproduced on iPad2 + iOS9 + Safari Mobile.

**Comment by pixelzoom** [comment] 2017-05-03 22:16
Reproduced on Win7 (VMware) + IE11.

**Comment by pixelzoom** [comment] 2017-05-03 22:55
Discussed with @jonathanolson via Skype.  Rather than the workaround in https://github.com/phetsims/function-builder-basics/issues/18#issuecomment-299042863, a better solution might be to require all of the images (png files) to have even dimensions.  And there seem to be even more general "symmetry" problems with most of the card images, which need to be addressed in https://github.com/phetsims/function-builder/issues/109.

**Comment by pixelzoom** [comment] 2017-05-03 22:57
Discussed and debugged with @jonathanolson via Skype.  The problem in not sub-pixel positioning, it's antialiasing. 

The solution in https://github.com/phetsims/function-builder-basics/issues/18#issuecomment-299042863 has a problem. If we add 1 pixel of padding, then images will shift when Mirror (or other reflection) is applied.  A better solution is to require all of the images (png files) to have even dimensions.  And there seem to be even more general "symmetry" problems with most of the card images, which need to be addressed in https://github.com/phetsims/function-builder/issues/109.

**Comment by pixelzoom** [comment] 2017-05-03 22:58
Discussed and debugged with @jonathanolson via Skype. The problem in not sub-pixel positioning, it's antialiasing.

The solution in #18 (comment) has a problem. If we add 1 pixel of padding, then images will shift when Mirror (or other reflection) is applied. A better solution is to require all of the images (png files) to have even dimensions.

And related to Mirror... There seems to be a general "symmetry" problem with most of the card images, which needs to be addressed in phetsims/function-builder#109.

**Comment by pixelzoom** [comment] 2017-05-04 16:49
To address this issue:

(1) Revise .png files for all card images so that they have even dimensions.

(2) Add an assertion to  `FBCanvasUtils.createCanvasWithImage` verifying that the `image` argument has even dimensions.  

Ideally, this should be addressed at the same time as phetsims/function-builder#109, since that issue also requires significant changes to (some) card images.

**Comment by pixelzoom** [comment] 2017-05-04 16:55
@amanda-phet What's your feeling about the priority of this issue? Should it be addressed before publishing Function Builder: Basics?  Does it require a maintenance release of Function Builder?

**Comment by amanda-phet** [comment] 2017-05-04 17:06
I just gave it a shot with the snowflake and it's a pretty frustrating task, so I'd prefer to let our graphic artist handle it :) If she can address the issues with the images and get back to us within a week I think we should absolutely address it for Function Builder: Basics and later this summer we can do a maintenance release for Function Builder (along with any other issues sitting around for that sim). Let me reach out to Cheryl and see what she thinks.

**Comment by pixelzoom** [comment] 2017-05-17 21:56
Further discussion and revision of the artwork is being addressed in https://github.com/phetsims/function-builder/issues/109.

**Comment by pixelzoom** [comment] 2017-06-05 21:31
This was addressed and verified in https://github.com/phetsims/function-builder/issues/109.

Closing.

**Closed as completed by pixelzoom** 2017-06-05 21:31 UTC
Labels: type:bug, design:artwork
