### ISSUE TITLE
Usability on small screen review

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/function-builder-basics#23] opened 2019-04-16 18:25 UTC
Per @kathy-phet's request in https://github.com/phetsims/QA/issues/295 I am making issues in each published sim repo detailing the pointer areas and usability of sims on phone sized screens.  Done on an iPhone 7 iOS 12 device.

Potential Difficulties Noticed:
* Carousel dots couldn't really be pressed

Screenshots:
![Image from iOS (1)](https://user-images.githubusercontent.com/41024075/56234518-ad1d5700-6042-11e9-8bef-e6afd70757bd.png)
![Image from iOS (2)](https://user-images.githubusercontent.com/41024075/56234520-adb5ed80-6042-11e9-836e-8669b66bda03.png)
![Image from iOS](https://user-images.githubusercontent.com/41024075/56234522-adb5ed80-6042-11e9-823f-6c3f81e0d8fd.png)

**Comment by pixelzoom** [comment] 2019-04-16 19:42
Duplicate of https://github.com/phetsims/function-builder/issues/125; whatever we decide for function-builder will apply to this sim.

**Closed as completed by pixelzoom** 2019-04-16 19:42 UTC
Labels: type:duplicate
